name: video_trim_example
description: Demonstrates how to use the video_trim plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_trim:
    path: ../

  cupertino_icons: ^1.0.2
  file_picker: ^8.0.7
  video_player: ^2.9.5
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
