name: video_trimmer_2_example
description: Demonstrates how to use the video_trimmer_2 plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_trimmer_2:
    path: ../

  cupertino_icons: ^1.0.2
  file_picker: ^8.0.7
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
