name: video_trim
description: A Flutter plugin to trim videos on Android and iOS. An alternate to ffmpeg to trim and export videos.
version: 0.1.1
homepage: https://github.com/ketanvagh0699/video_trim.git
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.1.0
  video_player: ^2.9.5
  flutter_video_thumbnail_plus: ^1.0.5
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kv.video_trim
        pluginClass: VideoTrimPlugin
      ios:
        pluginClass: VideoTrimPlugin
